-- SP Mobile Detailing — Database Schema
-- Run this in Supabase Dashboard → SQL Editor
-- This creates the bookings + availability tables matching the 207 Barbershop pattern

-- ===== BOOKINGS TABLE =====
CREATE TABLE IF NOT EXISTS public.bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service text NOT NULL,
  price text,
  date text NOT NULL,
  time text NOT NULL,
  customer_name text NOT NULL,
  customer_email text,
  customer_phone text NOT NULL,
  vehicle text,
  location text,
  notes text,
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')),
  created_at timestamptz DEFAULT now()
);

-- ===== AVAILABILITY TABLE =====
CREATE TABLE IF NOT EXISTS public.availability (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_of_week integer NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  is_active boolean DEFAULT false,
  start_time text DEFAULT '8:00 AM',
  end_time text DEFAULT '5:00 PM',
  slot_duration integer DEFAULT 60,
  UNIQUE (day_of_week)
);

-- ===== BLOCKED DATES TABLE =====
CREATE TABLE IF NOT EXISTS public.blocked_dates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date text NOT NULL,
  reason text,
  created_at timestamptz DEFAULT now()
);

-- ===== SEED DEFAULT AVAILABILITY =====
-- Mon-Sat active, Sunday off
INSERT INTO public.availability (day_of_week, is_active, start_time, end_time, slot_duration)
VALUES
  (0, false, '8:00 AM', '5:00 PM', 60),  -- Sunday: Off
  (1, true,  '8:00 AM', '5:00 PM', 60),  -- Monday
  (2, true,  '8:00 AM', '5:00 PM', 60),  -- Tuesday
  (3, true,  '8:00 AM', '5:00 PM', 60),  -- Wednesday
  (4, true,  '8:00 AM', '5:00 PM', 60),  -- Thursday
  (5, true,  '8:00 AM', '5:00 PM', 60),  -- Friday
  (6, true,  '9:00 AM', '3:00 PM', 60)   -- Saturday
ON CONFLICT (day_of_week) DO NOTHING;

-- ===== ROW LEVEL SECURITY =====
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocked_dates ENABLE ROW LEVEL SECURITY;

-- Bookings: anyone can insert (customers), authenticated users can read/update/delete
CREATE POLICY "Anyone can insert bookings" ON public.bookings
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Authenticated users can view bookings" ON public.bookings
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update bookings" ON public.bookings
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete bookings" ON public.bookings
  FOR DELETE USING (auth.role() = 'authenticated');

-- Availability: anyone can read (for booking form), authenticated can modify
CREATE POLICY "Anyone can read availability" ON public.availability
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can update availability" ON public.availability
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert availability" ON public.availability
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Blocked dates: anyone can read, authenticated can modify
CREATE POLICY "Anyone can read blocked dates" ON public.blocked_dates
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert blocked dates" ON public.blocked_dates
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete blocked dates" ON public.blocked_dates
  FOR DELETE USING (auth.role() = 'authenticated');
